default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ubuntu
  password: Peaceful1
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test

production:
  <<: *default
  database: sample_app_production